#Demo on play level variable
- name: Variable demo
  hosts: all
  vars:
    URL_A: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL_A }}

#Demo on task level variable
- name: Variable demo task level
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: play1.example.com

