## Demo Variable print task
- name: Demo on Play level Variables
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

## Demo inline vars task
- name: Demo on Task level Variables
  hosts: all
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}
      vars:
        URL: play.example.com

